config/routes.rb
Rails.application.routes.draw do

  root 'sub_reddits#index'

  resources :sub_reddits do
      resources :posts do
          resources :comments
      end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :parent, :class_name => "Comment", :required => false
    has_many :comments, :foreign_key => "parent_id"
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
    belongs_to :sub_reddit
end

app/models/sub_reddit.rb
class SubReddit < ApplicationRecord
    has_many :posts

    scope :sorted, lambda { order(:created_at => "DESC") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @post = Post.find_by_id(params[:post_id])
        @comment = @post.comments.create(comment_params)

        if @comment.save
            flash[:notice] = "Comment added"
            redirect_to sub_reddit_post_path(@post.sub_reddit, @post)
        else
            flash[:error] = "Error creating comment"
            redirect_to sub_reddit_post_path(@post.sub_reddit, @post)
        end
    end

    private

    def comment_params
        params.require(:comment).permit(:parent_id, :text, :name, :link, :email)
    end
end

app/controllers/posts_controller.rb
require 'screencap'

class PostsController < ApplicationController
    def show
        @post = Post.find_by_id(params[:id])
        @comments = @post.comments.where(:parent_id => nil)
    end

    def new
        @sub_reddit = SubReddit.find_by_id(params[:sub_reddit_id])
        @post = Post.new()
    end

    def create
        @sub_reddit = SubReddit.find_by_id(params[:sub_reddit_id])
        @post = @sub_reddit.posts.create(post_params)

        if @post.save
            flash[:notice] = "Post added"
            redirect_to sub_reddit_post_path(@sub_reddit, @post)
        else
            flash[:error] = "Error creating comment"
            redirect_to new_sub_reddit_post(@sub_reddit, @post)
        end
    end

    private

    def post_params
        params.require(:post).permit(:title, :link, :description)
    end
end

app/controllers/sub_reddits_controller.rb
class SubRedditsController < ApplicationController
  def index
      @sub_reddits = SubReddit.sorted
  end

  def show
      @sub_reddit = SubReddit.find_by_id(params[:id])
  end

  def new
      @sub_reddit = SubReddit.new()
  end

  def create
      @sub_reddit = SubReddit.new(sub_reddit_params)

      if @sub_reddit.save
          flash[:notice] = "Sub Reddit added"
          redirect_to sub_reddit_path(@sub_reddit)
      else
          flash[:error] = "Error creating comment"
          redirect_to new_sub_reddit_path()
      end
  end

  private

  def sub_reddit_params
      params.require(:sub_reddit).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/sub_reddit_helper.rb
module SubRedditHelper
end

app/views/comments/_form.html.erb
<%= form_tag(sub_reddit_post_comments_path(post_id: post_id)) do %>
    <% fields_for :comment do |f| %>
        <% if parent_id %>
            <%= f.hidden_field(:parent_id, :value => parent_id) %>
        <% end %>
        <div class="row margin-bottom-20">
            <div class="form-group">
                <div class="col-xs-6 col-md-3">
                    <%= f.label(:name, "Name") %>
                </div>
                <div class="col-xs-6 col-md-3">
                    <%= f.text_field(:name, :class => "form-control") %>
                </div>
            </div>
        </div>

        <div class="row margin-bottom-20">
            <div class="form-group">
                <div class="col-xs-6 col-md-3">
                    <%= f.label(:email, "Your email address") %>
                </div>
                <div class="col-xs-6 col-md-3">
                    <%= f.text_field(:email, :class => "form-control") %>
                </div>
            </div>
        </div>

        <div class="row margin-bottom-20">
            <div class="form-group">
                <div class="col-xs-6 col-md-3">
                    <%= f.label(:link, "Include a Link") %>
                </div>
                <div class="col-xs-6 col-md-3">
                    <%= f.text_field(:link, :class => "form-control") %>
                </div>
            </div>
        </div>

        <div class="row margin-bottom-20">
            <div class="form-group">
                <div class="col-xs-6 col-md-3">
                    <%= f.label(:text, "Your Comment") %>
                </div>
                <div class="col-xs-6 col-md-3">
                    <%= f.text_area(:text, :class => "form-control") %>
                </div>
            </div>
        </div>

        <div class="row margin-bottom-20">
            <div class="col-xs-6 col-xs-offset-6 col-md-3 col-md-offset-3">
                <%= f.submit("Add a comment", :class => "btn btn-sm btn-primary") %>
            </div>
        </div>
    <% end %>
<% end %>

app/views/comments/_show.html.erb
<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title"><%= comment.name %> says:</h3>
    </div>
    <div class="panel-body">
        <p><%= comment.text %></p>
        <%= link_to("Visit my site", comment.link, :class => "btn btn-sm btn-info") %>
    </div>
    <div class="panel-footer">
        posted <%= comment.created_at.to_formatted_s %>
        <button class="btn pull-right btn-sm btn-default add-comment" data-add-label="Add reply">Add reply</button>
        <div class="collapse comment-form">
            <%= render(:partial => 'comments/form', :locals => {:post_id => comment.post_id, :parent_id => comment.id}) %>
        </div>
    </div>
</div>

<ul>
    <% comment.comments.each do |reply| %>
        <li><%= render(:partial => 'comments/show', :locals => {:comment => reply}) %></li>
    <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Freddit</title>
    <%= csrf_meta_tags %>

    <!-- Reset CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <header>
        <div class="container">
            <h1><%= link_to("Freddit", root_path) %></h1>
        </div>
    </header>
    <div class="container">
        <% if flash[:notice] %>
            <div class="alert alert-success margin-top-20" role="alert">
                <strong>Success</strong> <%= flash[:notice] %>
            </div>
        <% end %>
        <% if flash[:error] %>
            <div class="alert alert-danger margin-top-20" role="alert">
                <strong>Error</strong> <%= flash[:error] %>
            </div>
        <% end %>
        <div class="row">
            <div class="col-xs-12">
            </div>
        </div>
        <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</body>
</html>

app/views/posts/new.html.erb
<div class="row">
    <div class="col-xs-12">
        <p><%= link_to("<span class=\"glyphicon glyphicon-arrow-left\"></span>Back to topic".html_safe, sub_reddit_path(@sub_reddit), :class => "btn btn-default margin-top-20") %></p>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <h2>Create Post</h2>
    </div>
</div>

<%= form_for(@post, url: sub_reddit_posts_path) do |f| %>
<div class="row form-group margin-bottom-20 margin-top-40">
    <div class="col-xs-6 col-md-3">
        <%= f.label(:title, "Post Title") %>
    </div>
    <div class="col-xs-6 col-md-3">
        <%= f.text_field(:title, :class => "form-control") %>
    </div>
</div>

<div class="row form-group margin-bottom-20">
    <div class="col-xs-6 col-md-3">
        <%= f.label(:link, "Link") %>
    </div>
    <div class="col-xs-6 col-md-3">
        <%= f.text_field(:link, :class => "form-control") %>
    </div>
</div>

<div class="row form-group margin-bottom-20">
    <div class="col-xs-6 col-md-3">
        <%= f.label(:description, "Description") %>
    </div>
    <div class="col-xs-6 col-md-3">
        <%= f.text_area(:description, :class => "form-control") %>
    </div>
</div>

<div class="row">
    <div class="col-xs-6 col-xs-offset-6 col-md-3 col-md-offset-3">
        <%= f.submit("Create Post", :class => "btn btn-sm btn-primary") %>
    </div>
</div>

<% end %>

app/views/posts/show.html.erb
<div class="row">
    <div class="col-xs-12">
        <p><%= link_to("<span class=\"glyphicon glyphicon-arrow-left\"></span>Back to topics".html_safe, sub_reddit_path(@post.sub_reddit), :class => "btn btn-default margin-top-20") %></p>
    </div>
</div>

<div class="row margin-bottom-40">
    <div class="col-xs-12">
        <h2><%= @post.title %></h2>
        <p><%= @post.description %></p>
        <p><%= link_to("View site", @post.link, :class => "btn btn-info") %></p>
    </div>
</div>

<div class="row margin-bottom-40">
    <div class="col-xs-12">
        <h3>Comments</h3>
    </div>
</div>

<button class="btn btn-sm btn-default add-comment margin-bottom-40" data-add-label="Add comment">Add comment</button>
<div class="collapse comment-form">
    <%= render(:partial => 'comments/form', :locals => {:post_id => @post.id, :parent_id => false}) %>
</div>

<div class="row">
    <div class="col-xs-12">
        <ul>
            <% @comments.each do |comment| %>
                <li><%= render(:partial => 'comments/show', :locals => {:comment => comment}) %></li>
            <% end %>
        </ul>
    </div>
</div>

app/views/sub_reddits/index.html.erb
<div class="row">
    <div class="col-xs-6">
        <h2>All topics</h2>
    </div>
    <div class="col-xs-6">
        <%= link_to("Create new topic", new_sub_reddit_path(), :class => "pull-right btn btn-default margin-top-20") %>
    </div>
</div>

<div class="row margin-top-40">
    <% @sub_reddits.each do |sub_reddit| %>
        <div class="col-xs-6 col-sm-4 col-md-3">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title"><%= sub_reddit.title %></h3>
                </div>
                <div class="panel-body">
                    <p><%= truncate(sub_reddit.description) %></p>
                    <%= link_to("View topic", sub_reddit_path(sub_reddit), :class => "pull-right btn btn-info margin-top-20") %>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/sub_reddits/new.html.erb
<div class="row">
    <div class="col-xs-12">
        <p><%= link_to("<span class=\"glyphicon glyphicon-arrow-left\"></span>Back to topics".html_safe, sub_reddits_path(), :class => "btn btn-default margin-top-20") %></p>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <h2>Create Topic</h2>
    </div>
</div>

<%= form_for(@sub_reddit) do |f| %>
<div class="row form-group margin-bottom-20 margin-top-40">
    <div class="col-xs-6 col-md-3">
        <%= f.label(:title, "Topic Title") %>
    </div>
    <div class="col-xs-6 col-md-3">
        <%= f.text_field(:title, :class => "form-control") %>
    </div>
</div>

<div class="row form-group margin-bottom-20">
    <div class="col-xs-6 col-md-3">
        <%= f.label(:description, "Topic Description") %>
    </div>
    <div class="col-xs-6 col-md-3">
        <%= f.text_area(:description, :class => "form-control") %>
    </div>
</div>

<div class="row">
    <div class="col-xs-6 col-xs-offset-6 col-md-3 col-md-offset-3">
        <%= f.submit("Create Topic", :class => "btn btn-sm btn-primary") %>
    </div>
</div>

<% end %>

app/views/sub_reddits/show.html.erb
<div class="row">
    <div class="col-xs-12">
        <p><%= link_to("<span class=\"glyphicon glyphicon-arrow-left\"></span>Back to topics".html_safe, sub_reddits_path(), :class => "btn btn-default margin-top-20") %></p>
    </div>
</div>

<div class="row">
    <div class="col-xs-6">
        <h2><%= @sub_reddit.title %></h2>
    </div>
    <div class="col-xs-6">
        <%= link_to("Create a new Post", new_sub_reddit_post_path(@sub_reddit), :class => "pull-right btn btn-default margin-top-20") %>
    </div>
</div>

<div class="row margin-top-40">
    <% @sub_reddit.posts.each do |post| %>
        <div class="col-xs-6 col-sm-4 col-md-3">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title"><%= post.title %></h3>
                </div>
                <div class="panel-body">
                    <p><%= truncate(post.description) %></p>
                    <%= link_to("View full post", sub_reddit_post_path(@sub_reddit, post), :class => "btn btn-info pull-right margin-top-20") %>
                </div>
            </div>
        </div>
    <% end %>
</div>